site_name: Architecture Specs
site_url: https://archspecs.com/
repo_url: https://github.com/venugosv/architecture
nav:
    - Home: index.md
    - Increments:
      - DCVV2 In-House: 042 - DCVV2 In-house.md
theme:
    name: material
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "_"
    - plantuml_markdown:
plugins:
  - search
  - techdocs-core
